const express = require('express');
const router = express.Router();
const ExcelJS = require('exceljs');
const pool = require('../db/pool');
const { authenticate } = require('../middleware/auth');
const { generateSql } = require('../services/textToSql');

/**
 * Helper to wrap SQL with user isolation
 */
function enforceIsolation(sql, userId, userRole) {
    if (userRole === 'admin') return sql;

    // Check if isolation is already present in the SQL generated by the model
    const hasIsolation = sql.toLowerCase().includes('f.user_id =') || sql.toLowerCase().includes('current_user_id()');
    
    // If the model already added a user_id filter, we just replace its placeholder with the real ID
    if (hasIsolation) {
        return sql.replace(/current_user_id\(\)/gi, userId)
                  .replace(/f\.user_id\s*=\s*\d+/gi, `f.user_id = ${userId}`);
    }

    const isolationFilter = `(f.user_id = ${userId} OR f.id IN (SELECT form_id FROM form_permissions WHERE user_id = ${userId} AND status = 'approved'))`;
    
    // Ensure the SQL actually has the forms join if we are going to use 'f'
    let finalSql = sql;
    if (!sql.toLowerCase().includes('join forms f')) {
        // If the AI forgot the join, we must inject it for safety
        finalSql = sql.replace(/from submissions s/i, 'FROM submissions s JOIN form_versions fv ON s.form_version_id = fv.id JOIN forms f ON fv.form_id = f.id');
    }

    const hasWhere = finalSql.toLowerCase().includes('where');
    
    if (hasWhere) {
        return finalSql.replace(/where/i, `WHERE ${isolationFilter} AND `);
    } else {
        if (finalSql.toLowerCase().includes('group by')) {
            return finalSql.replace(/group by/i, `WHERE ${isolationFilter} GROUP BY`);
        }
        if (finalSql.toLowerCase().includes('order by')) {
            return finalSql.replace(/order by/i, `WHERE ${isolationFilter} ORDER BY`);
        }
        return `${finalSql} WHERE ${isolationFilter}`;
    }
}

/**
 * @route GET /api/explorer/schema
 * @desc  Get all forms and unique field labels the user has access to
 * @access Private
 */
router.get('/schema', authenticate, async (req, res) => {
    try {
        // 1. Get forms the user has access to (Owner, Admin, or Approved)
        const formsResult = await pool.query(`
            SELECT f.id, f.name 
            FROM forms f
            LEFT JOIN form_permissions fp ON f.id = fp.form_id AND fp.user_id = $1
            WHERE f.user_id = $1 
               OR $2 = 'admin' 
               OR (fp.user_id = $1 AND fp.status = 'approved')
            ORDER BY f.name ASC
        `, [req.user.id, req.user.role]);

        const formIds = formsResult.rows.map(f => f.id);

        if (formIds.length === 0) {
            return res.json({ forms: [], fields: [] });
        }

        // 2. Get unique field labels across those forms (using latest version for each)
        const fieldsResult = await pool.query(`
            SELECT DISTINCT label 
            FROM form_fields 
            WHERE form_version_id IN (
                SELECT fv.id 
                FROM form_versions fv
                INNER JOIN (
                    SELECT form_id, MAX(version_number) as max_v
                    FROM form_versions
                    WHERE form_id = ANY($1)
                    GROUP BY form_id
                ) latest ON fv.form_id = latest.form_id AND fv.version_number = latest.max_v
            )
            ORDER BY label ASC
        `, [formIds]);

        res.json({
            forms: formsResult.rows,
            fields: fieldsResult.rows.map(r => r.label)
        });
    } catch (err) {
        console.error('❌ Schema Error:', err);
        res.status(500).json({ error: 'Failed to fetch explorer schema' });
    }
});

/**
 * @route POST /api/explorer/query
 * @desc  Translate natural language to SQL and execute it (Isolated)
 * @access Private
 */
router.post('/query', authenticate, async (req, res) => {
    try {
        const { prompt, selectedForms } = req.body;
        if (!prompt) {
            return res.status(400).json({ error: 'Prompt is required' });
        }

        // 1. Generate SQL from prompt (passing context if available)
        let sql = await generateSql(prompt, selectedForms);
        if (!sql) {
            return res.status(500).json({ error: 'Failed to generate SQL' });
        }

        // 2. Enforce Security Isolation
        sql = enforceIsolation(sql, req.user.id, req.user.role);
        console.log(`📡 [USER:${req.user.username}] AI SQL: ${sql}`);

        // 3. Execute SQL
        const result = await pool.query(sql);

        res.json({
            sql: sql,
            rowCount: result.rowCount,
            rows: result.rows
        });

    } catch (err) {
        console.error('❌ Explorer Error:', err);
        res.status(500).json({ 
            error: 'AI Query failed',
            details: err.message
        });
    }
});

/**
 * @route POST /api/explorer/export
 * @desc  Export AI results to Excel
 * @access Private
 */
router.post('/export', authenticate, async (req, res) => {
    try {
        const { prompt, selectedForms } = req.body;
        if (!prompt) return res.status(400).json({ error: 'Prompt is required' });

        let sql = await generateSql(prompt, selectedForms);
        if (!sql) return res.status(500).json({ error: 'Failed to generate SQL' });
        
        sql = enforceIsolation(sql, req.user.id, req.user.role);
        const result = await pool.query(sql);

        if (result.rows.length === 0) {
            return res.status(404).json({ error: 'No data to export' });
        }

        const workbook = new ExcelJS.Workbook();
        const worksheet = workbook.addWorksheet('AI Query Results');

        // Logic to extract all possible keys from the 'Data' column across all rows
        const dataKeys = new Set();
        result.rows.forEach(row => {
            if (row.Data && typeof row.Data === 'object') {
                Object.keys(row.Data).forEach(k => dataKeys.add(k));
            }
        });

        // Create headers: [Fixed Columns] + [Dynamic Field Columns]
        const fixedHeaders = Object.keys(result.rows[0]).filter(k => k !== 'Data');
        const dynamicHeaders = Array.from(dataKeys).sort();
        const allHeaders = [...fixedHeaders, ...dynamicHeaders];

        worksheet.columns = allHeaders.map(h => ({ header: h, key: h, width: 25 }));

        // Add rows
        result.rows.forEach(row => {
            const cleanedRow = {};
            
            // 1. Process fixed columns
            fixedHeaders.forEach(k => {
                let val = row[k];
                if (typeof val === 'string') val = val.replace(/ \|\|\| /g, ', ');
                cleanedRow[k] = val;
            });

            // 2. Process dynamic Data columns
            if (row.Data && typeof row.Data === 'object') {
                dynamicHeaders.forEach(k => {
                    let val = row.Data[k] || '';
                    if (typeof val === 'string') val = val.replace(/ \|\|\| /g, ', ');
                    cleanedRow[k] = val;
                });
            }

            worksheet.addRow(cleanedRow);
        });

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename="ai_explorer_export.xlsx"`);
        
        await workbook.xlsx.write(res);
        res.end();

    } catch (err) {
        console.error('❌ Explorer Export Error:', err);
        res.status(500).json({ error: 'Export failed' });
    }
});

module.exports = router;
